config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#top'
  get 'about' => 'home#about'
  get 'how_to' => 'home#how_to'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users,:only => [:show]

  # resources :users,:only => [:update, :edit, :create, :show]
  # get 'signup' => 'users#new'
  # get 'users' => 'users#new'
  # get 'login' => 'users#login_form'
  # post 'login' => 'users#login'
  # post 'logout' => 'users#logout'
  # get 'users/:id/likes' => 'users#likes'
  # get 'users/:id/wants' => 'users#wants'

  post "wants/:item_id/create" => "wants#create"
  post "wants/:item_id/destroy" => "wants#destroy"
  
  post "likes/:item_id/create" => "likes#create"
  post "likes/:item_id/destroy" => "likes#destroy"
    
  get 'items/index' => 'items#index'
  get 'items/search_results' => 'items#search_results'
  resources :items, :except =>[:index] do
    resources :images
    resources :comments, only: [:create, :destroy]
  end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  validates :content, {presence: true, length: {minimum: 1, maximum: 300}}
  validates :buy_place, {length: {maximum: 50}}
  validates :price, {numericality: {only_integer: true} }
  validates :user_id, {presence: true}
    
  belongs_to :user
  has_many :likes
  has_many :comments
  has_many :wants
  has_many :images

  has_many :item_categories, dependent: :destroy
  has_many :categories, through: :item_categories

  accepts_nested_attributes_for :images

  def save_categories(tags)
    current_tags = self.categories.pluck(:name) unless self.categories.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.categories.delete Category.find_by(name:old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      article_category = Category.find_or_create_by(name:new_name)
      self.categories << article_category
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}
    
  def index
    @items = Item.all.order(created_at: :desc)

    @search = Item.ransack(params[:q])
    @result = @search.result(distinct: true).order(created_at: :desc)
  end
   
  def show
    @item = Item.find_by(id: params[:id])
    @user = @item.user
      
    @likes_count = Like.where(item_id: @item.id).count
    @wants_count = Want.where(item_id: @item.id).count
      
    @comments = @item.comments
    @comment = Comment.new
  end
    
  def new
    @item = Item.new
    # @item.images.build
  end
    
   def create
    @item = @current_user.items.build(item_params)
    category_list = params[:category_list].split(",")

    @item.images.each_with_index do |image, i|
        if i == 0
            image.main_image = true
        else
            image.main_image = false
        end
    end
       
    if @item.save
      @item.save_categories(category_list)
      flash[:notice] = "投稿を作成しました"
      redirect_to("/items/index")
    else
      render("items/new")
    end
  end    
   
  def edit
    @category_list = @item.categories.pluck(:name).join(",")
  end
    
  def update
    @item = Item.find(params[:id])  

    category_list = params[:category_list].split(",")
  
    if @item.update(item_update_params)
        @item.save_categories(category_list)
        flash[:notice] = '投稿を編集しました'
        redirect_to(item_path(@item.id))
    else
        render('items/edit')
    end  
  end
    
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
      
    @item.images.each do |i|
      i.destroy
    end
    
    flash[:notice] = '投稿を削除しました'
    redirect_to("/items/index")
      
  end
    
 def ensure_correct_user
     @item = Item.find_by(id: params[:id])
     
     unless @current_user.has_item?(@item)
      flash[:notice] = "権限がありません"
      redirect_to(items_path)
     end
 end

 def search_results
 end
    
 private
    
  def item_params
      params.require(:item).permit(:content, :buy_place, :price, images_attributes: [:id, {image_name: []}, :main_image])
  end
    
   def item_update_params
      params.require(:item).permit(:content, :buy_place, :price, images_attributes: [:id, :image_name, {image_name: []}])
  end
  
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="main">    
    <div class="container">
        <div><h2>投稿を編集する</h2></div>
        　
        <%= form_with model: @item, local: true do |f| %>
            <div class='form'>
            <div class = 'form_content'>
            <p><%= f.label :content, '内容' %></p>
            <%= f.text_area :content %>
            </div>
            
            <div class = 'form_content'>
            <p><%= f.label :buy_place, '購入場所' %></p>
            <%= f.text_field :buy_place %>
            </div>
                
            <div class = 'form_content'>
            <p><%= f.label :price, '価格' %></p>
            <%= f.text_field :price %>円
            </div>
                
            <div class="item-tags-field">
                <%= f.label "カテゴリ" %>
                <ul id="item-tags">
                </ul>
                <%= hidden_field_tag :category_hidden,@category_list %>
            </div>

            <div class = 'form_content'>
            <%= f.fields_for :images do |image| %>
                <% if image.index == 0 %>
                <p><%= image.label :image_name, 'メイン画像' %></p>
                <% else %>
                <p><%= image.label :image_name, '画像' %></p>
                <% end %>

                <%= image.file_field :image_name, multiple: true, type: 'file', name: "images[image_name]" %>
                
                <% if image.index == 0 %>
                <%= image.hidden_field :main_image, value: true %>
                <% else %>
                <%= image.hidden_field :main_image, value: false %>
                <% end %>
            <% end %>
                
                <%= f.submit '投稿を変更' %>
            </div>
                
            </div>
        <% end %>  

    </div>
</div>

app/views/items/index.html.erb
<div class="main items-index">
    <div class="container">
        <div class="search">
            <div class="search_bottom" onclick="obj=document.getElementById('open').style; obj.display=(obj.display=='none')?'block':'none';">
                <a style="cursor:pointer;"><h2>▼ 検索</h2></a>
            </div>
            <div id="open" style="display:none;clear:both;">
                <%= search_form_for @search, url: items_index_path do |search| %>
                    <div class="search_content">
                        <%= search.label :user_name_cont, "ユーザー名" %>
                        <%= search.search_field :user_name_cont %>
                    </div>

                    <div class="search_content">
                        <%= search.label :content_cont, "内容" %>
                        <%= search.search_field :content_cont %>
                    </div>

                    <div class="search_content">
                        <%= search.label :buy_place_cont, "購入場所" %>
                        <%= search.search_field :buy_place_cont %>
                    </div>

                    <div class="search_content">
                        <%= search.label :price_gteq, "価格" %>
                        <%= search.search_field :price_gteq %>
                        <%= "円以上〜" %>
                        <%= search.search_field :price_lt %>
                        <%= "円未満" %>
                    </div>

                    <div class="search_content">
                        <%= search.label :categories_name_cont, "カテゴリー" %>
                        <%= search.search_field :categories_name_cont %>
                    </div>

                    <%= search.submit "検索" %>
                <% end %>
            </div>
        </div>
        
        <% if @result.present? %>
            <% @result.each do |r| %>
                <div class="items-index-content">
                    <p><%= link_to(r.user.name, user_path(r.user.id)) %></p>
                    <p>
                        <% r.images.each do |image| %>
                            <% if image.main_image? %>
                                <%= image_tag "/uploads/image/image_name/#{image.id}/item_image.jpg" %>
                            <% end %>
                        <% end %>
                    </p>
                    <p>内容：<%= link_to(r.content, item_path(r.id)) %></p>
                    <p>
                        <% if r.buy_place.blank? %>
                            購入場所：<%= link_to("購入場所不明", item_path(r.id)) %>
                        <% else %>
                            購入場所：<%= link_to(r.buy_place, item_path(r.id)) %>
                        <% end %>
                    </p>
                    <p>価格：<%= link_to(r.price, item_path(r.id)) %></p>

                    <% if r.categories.present? %>
                        <p>カテゴリー：
                            <% r.categories.each do |category| %>
                                <%= category.name %>
                            <% end %>
                        </p>
                    <% end %>
                </div>
            <% end %>
        <% else %>
            <p class="error_message">検索結果なし</p>
            <% @items.each do |item| %>
                <div class="items-index-content">

                    <p><%= link_to(item.user.name, user_path(item.user.id)) %></p>
                    <p>
                        <% item.images.each do |image| %>
                            <% if image.main_image? %>
                                <%= image_tag "/uploads/image/image_name/#{image.id}/item_image.jpg" %>
                            <% end %>
                        <% end %>
                    </p>
                    <p>内容：<%= link_to(item.content, item_path(item.id)) %></p>
                    <p>
                        <% if item.buy_place.blank? %>
                            購入場所：<%= link_to("購入場所不明", item_path(item.id)) %>
                        <% else %>
                            購入場所：<%= link_to(item.buy_place, item_path(item.id)) %>
                        <% end %>
                    </p>
                    <p>価格：<%= link_to(item.price, item_path(item.id)) %></p>

                    <% if item.categories.present? %>
                        <p>カテゴリー：
                            <% item.categories.each do |category| %>
                                <%= category.name %>
                            <% end %>
                        </p>
                    <% end %>
                </div>
            <% end %>
    <% end %>
    </div>
</div>

app/views/items/new.html.erb
<div class="main">
    <div class="container">
    <div><h2>投稿する</h2></div>
    　
    <%= form_with model: @item, local: true do |f| %>
        <div class='form'>
            
        <p><%= f.label :content, '内容' %></p>
            <%= f.text_area :content %>

            <p><%= f.label :buy_place, '購入場所' %></p>
            <%= f.text_field :buy_place %>

            <p><%= f.label :price, '価格' %></p>
            <%= f.text_field :price %>円

            <div class="item-tags-field">
                <%= f.label "カテゴリー" %>
                <ul id="item-tags">
                </ul>
            </div> 
            
            <%= f.fields_for :images do |i| %>
            <p><%= i.label :image_name, 'メイン画像' %></p>
            <%= i.file_field :image_name, multiple: true %>
            <% end %>
        
            <%= f.fields_for :images do |i2| %>
            <p><%= i2.label :image_name, '画像' %></p>
            <%= i2.file_field :image_name, multiple: true %>
            <% end %>
            
            <%= f.fields_for :images do |i3| %>
            <p><%= i3.label :image_name, '画像' %></p>
            <%= i3.file_field :image_name, multiple: true %>
            <% end %>
            
            <%= f.submit '投稿' %>
        </div>
    <% end %>  

    </div>
</div>

app/views/items/search_results.html.erb
<h3>検索結果</h3>

app/views/items/show.html.erb
<div class="main items-show">   
    <div class="container">
        <div class="items-show-content">
            <p>
                <%= link_to(current_user.name, user_path(current_user.id)) %>
            </p>
            <p>
                画像<br>
                <% @item.images.each do |image| %>
                    <%= image_tag "/uploads/image/image_name/#{image.id}/item_image.jpg" %>
                <% end %>
            </p>
            <p>
                内容：<%= @item.content %>
            </p>
            <p>
                <% if @item.buy_place.blank? %>
                購入場所：購入場所不明
                <% else %>
                購入場所：<%= @item.buy_place %>
                <% end %>
            </p>
            <p>
                価格：<%= @item.price %>
            </p>

            <p>
                カテゴリー：
                <% @item.categories.each do |category| %>
                <%= category.name %>
                <% end %>
            </p>
            
            <% if Like.find_by(user_id: @current_user.id, item_id: @item.id) %>
                <%= link_to("/likes/#{@item.id}/destroy", {method: "post"}) do %>
                    <span class="fas fa-thumbs-up like-btn-unlike"></span>
                <% end %>
            <% else %>
                <%= link_to("/likes/#{@item.id}/create", {method: "post"}) do %>
                    <span class="fas fa-thumbs-up like-btn"></span>
                <% end %>
            <% end %>
            <%= @likes_count %>
                
            <% if Want.find_by(user_id: @current_user.id, item_id: @item.id) %>
                <%= link_to("/wants/#{@item.id}/destroy", {method: "post"}) do %>
                    <span class="fas fa-shopping-bag want-btn-unlike"></span>
                <% end %>
            <% else %>
                <%= link_to("/wants/#{@item.id}/create", {method: "post"}) do %>
                    <span class="fas fa-shopping-bag want-btn"></span>
                <% end %>
            <% end %>
            <%= @wants_count %>
            
            <div class="item-time">
                <%= @item.created_at.strftime("%Y-%m-%d %H:%M") %>
            </div>
                
            <% if @current_user.has_item?(@item) %>
                <div class="item-menus">
                    <%= link_to("編集", edit_item_path(@item.id)) %>
                    <%= link_to("削除", "/items/#{@item.id}", {method: "delete"}) %>
                </div>
            <% end %>
        </div>
            <br>
            <h2>コメント一覧</h2>
                <% @comment.errors.full_messages.each do |message| %>
                <div class="comment_error">
                <li><%= message %></li>
                </div>
                <% end %>

                <div class="comment">
                    <% @comments.each do |comment| %>
                        <div>
                            <%= link_to("/users/#{comment.user_id}") do %>
                                <%= image_tag "/user_images/#{comment.user.image_name}", size: '30x30' %>
                                &emsp;<%= comment.user.name %>
                            <% end %>
                            
                            <p><%= comment.content %></p>
                            <p>
                            <% if @current_user.has_comment?(comment) %>
                                <%= link_to item_comment_path(@item, comment), method: :delete do %>
                                <span>コメント削除</span>
                                <% end %>
                            <% end %>
                            </p>
                            <hr>
                        </div>
                    <% end %>

                    <%= form_with model:[@item, @comment], local: true do |f| %>
                    <%= f.text_field :content %>
                    <%= f.submit 'コメントする' %>
                    <% end %>
                </div>
    </div>
</div>